version: '3.9'
services:
  katsebi:
    container_name: katsebi-dev
    image: katsebi-dev
    restart: on-failure
    build:
      context: .
    ports:
      - "8085:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: katsebi.db